# Generated by Django 5.2 on 2025-05-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_rename_nama_dokter_medicalrecord_username_dh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='username_dh',
            new_name='nama_dokter',
        ),
    ]
