# Generated by Django 5.2 on 2025-05-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_rename_username_dh_medicalrecord_nama_dokter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='nama_dokter',
            new_name='username_dh',
        ),
    ]
