# Generated by Django 5.2 on 2025-05-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_rename_nama_dokter_medicalrecord_username_dh'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='id_hewan',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
