# Generated by Django 5.2 on 2025-05-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_medicalrecord_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcheckschedule',
            old_name='frekuensi_pemeriksaan_bulanan',
            new_name='freq_pemeriksaan_rutin',
        ),
    ]
